name: dikdur
description: "DİK DURACAKSIN."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter
  flutter_local_notifications: ^19.1.0
  get: ^4.7.2
  google_fonts: ^6.2.1
  numberpicker: ^2.1.2
  workmanager:
    git:
      url: https://github.com/fluttercommunity/flutter_workmanager.git
      path: workmanager
      ref: main
  firebase_core: ^2.25.4
  cloud_firestore: ^4.14.0
  firebase_storage: ^11.6.0
  http: ^1.3.0
  path_provider: ^2.1.1
  fluttertoast: ^8.2.2
  
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
      - assets/texts.txt
      - assets/imgs/1.jpg
      - assets/imgs/2.jpg
      - assets/imgs/3.jpg
